# Generated by Django 4.0.3 on 2022-04-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Women',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.TextField(blank=True)),
                ('age', models.IntegerField()),
                ('delete', models.BooleanField(default=False)),
                ('display', models.BooleanField(default=False)),
            ],
        ),
    ]
