# Generated by Django 4.0.3 on 2022-06-03 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_womenrelation_women_women_like_womenrelation_women'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='women_like',
            field=models.ManyToManyField(related_name='books', through='women.WomenRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BlackListJWT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('add', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
