# Generated by Django 4.0.3 on 2022-06-03 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_alter_women_women_like_blacklistjwt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='womenrelation',
            name='like',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='RefreshJWT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
